export const LANGUAGES: any = {
  '': '',
  albanska: 'Albanska',
  arabiska: 'Arabíska',
  bulgarska: 'Búlgarska',
  danska: 'Danska',
  eistneska: 'Eistneska',
  enska: 'Enska',
  faereyska: 'Færeyska',
  filippseyskt_mal: 'Filippseyskt mál',
  finnska: 'Finnska',
  franska: 'Franska',
  graenlenska: 'Grænlenska',
  griska: 'Gríska',
  hebreska: 'Hebreska',
  hindi: 'Hindi',
  hollenska: 'Hollenska',
  indonesiska: 'Indónesíska',
  islenska: 'Íslenska',
  italska: 'Ítalska',
  japanska: 'Japanska',
  kinverska: 'Kínverska',
  koreska: 'Kóreska',
  kurdiska: 'Kúrdíska',
  lettneska: 'Lettneska',
  litaiska: 'Litáíska',
  makedonska: 'Makedónska',
  mongolska: 'Mongólska',
  nepalska: 'Nepalska',
  norska: 'Norska',
  persneska: 'Persneska',
  polska: 'Pólska',
  portugalska: 'Portúgalska',
  rumenska: 'Rúmenska',
  russneska: 'Rússneska',
  saenska: 'Sænska',
  serbokroatiska: 'Serbókróatíska',
  singhalesiska: 'Singhalesíska',
  slovakiska: 'Slóvakíska',
  slovenska: 'Slóvenska',
  spaenska: 'Spænska',
  svahili: 'Svahilí',
  tailenska: 'Taílenska',
  tamil: 'Tamíl',
  tekkneska: 'Tékkneska',
  thyska: 'Þýska',
  tyrkneska: 'Tyrkneska',
  ukrainska: 'Úkraínska',
  ungverska: 'Ungverska',
  urdu: 'Úrdu',
  vietnamska: 'Víetnamska',
  annad: 'Annað',
};

export const AGES = {
  '': '',
  barn: '< 13',
  unglingur: '13 - 18',
  tvitugt: '19 - 29',
  thritugt: '30 - 39',
  fertugt: '40 - 49',
  fimmtugt: '50 - 59',
  sextugt: '60 - 69',
  sjotugt: '70 - 79',
  attraett: '80 - 89',
  niraett: '> 89',
};

export const SEXES = {
  '': '',
  annad: 'Annað',
  karl: 'Karl',
  kona: 'Kona',
};

export interface DemoInfo {
  sex: string;
  age: string;
  native_language: string;
}
