export const LANGUAGES: any = [
  'albanska',
  'arabiska',
  'bulgarska',
  'danska',
  'eistneska',
  'enska',
  'faereyska',
  'filippseyskt_mal',
  'finnska',
  'franska',
  'graenlenska',
  'griska',
  'hebreska',
  'hindi',
  'hollenska',
  'indonesiska',
  'islenska',
  'italska',
  'japanska',
  'kinverska',
  'koreska',
  'kurdiska',
  'lettneska',
  'litaiska',
  'makedonska',
  'mongolska',
  'nepalska',
  'norska',
  'persneska',
  'polska',
  'portugalska',
  'rumenska',
  'russneska',
  'saenska',
  'serbokroatiska',
  'singhalesiska',
  'slovakiska',
  'slovenska',
  'spaenska',
  'svahili',
  'tailenska',
  'tamil',
  'tekkneska',
  'thyska',
  'tyrkneska',
  'ukrainska',
  'ungverska',
  'urdu',
  'vietnamska',
  'annad',
];

export const AGES = [
  'barn',
  'unglingur',
  'tvitugt',
  'thritugt',
  'fertugt',
  'fimmtugt',
  'sextugt',
  'sjotugt',
  'attraett',
  'niraett',
];

export const SEXES = ['annad', 'karl', 'kona'];

export interface DemoInfo {
  sex: string;
  age: string;
  native_language: string;
}
