# Number of days of inactivity before an issue becomes stale
daysUntilStale: 730
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - neverclose
  - "Type: localization"
  - "Blocked: external"
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not been updated in 2 years. It will be closed if no further activity occurs within the next 30 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to lack of activity. Please feel free to re-open if you need further assistance.
only: issues
