export const up = async function (db: any): Promise<any> {
  return db.runSql(`
    UPDATE sentences SET is_used = FALSE WHERE locale_id=(SELECT id from locales WHERE name='lv') AND text in (
        'Brauksim uz tās kuces māju.',
        'Drusku gribas kakāt.',
        'Ej kniebies, ar ko vien gribi. Tu man neesi vajadzīgs.',
        'Es dzirdu, kā resnis skrien.',
        'Es nopirdos. Kā vīrs.',
        'Gan jau viņa grib nokniebties.',
        'Jā! Lien laukā, man vajag čurāt!',
        'Jā. Viņa ir kuce.',
        'Ko tas sīkais sūds ar mani darītu?',
        'Malā, resni!',
        'Man ir sūdīgs darbs, un esmu apmierināts.',
        'Meitene, atrodi vīrieti.',
        'Meitene, turi muti.',
        'Protams - kur skanošais, tur armēņi.',
        'Nekad neesmu uzticējies japāņiem.',
        'Tur smird kā dirsā.',
        'Draudziņ, esmu dzirdējis, ka viņa ir maita.',
        'Draņķi, kāpēc apkauno formastērpu?',
        'Ei! Tas mērglis tikko nozaga manas bikses!',
        'Ei, mērgli! Novācies no ceļa!',
        'Ej ellē, mērgli.',
        'Es arī, sūdabrāli.',
        'Es dievinu mīlu.',
        'Es domāju, ka tavs plāns ir sūds.',
        'Es domāju: Viņš ir tik skaists, ka patīkami satikt viņa vāverīti.',
        'Es esmu labais! Šauj viņu.',
        'Es tevi čakarēju?',
        'Forši šos piečakarēji.',
        'Ir divi sieviešu veidi, viegli un grūti iegūstamas.',
        'Ja piestāji vaktēt pēdas, ielaidīsi man lodi pakaļā.',
        'Jums bija tik daudz ieroču, lai iebruktu Sudānā.',
        'Jā. Diemžēl labākā dzerstiņu vieta pilsētā.',
        'Kad sāksies sūdi, es būšu gatavs, bet tu nē.',
        'Kas par maitu.',
        'Ko jūs esat sadomājuši, debīliķi?',
        'Ko tu dari, maita?',
        'Ko? Es esmu mērglis?',
        'Kura daļa "nogalina cilvēkus" tev nav skaidra?',
        'Laid vaļā, mērgli!',
        'Man nekas nav jāspēj. Esmu sūda lācis.',
        'Melnie bagātnieki taču nemēdz kļūdīties.',
        'Meties pliks, puika.',
        'Nepateicīgais lops.',
        'Pusotrs miljons palaistuvēm un viskijam, pārējais notriekts tāpat vien.',
        'Rokā esi, mērgli!',
        'Sūds, cerams nav pielādēts.',
        'Sūdu būšana.',
        'Tas ir robots, kas nogalina cilvēkus.',
        'Tava pakaļa būs manā mašīnā jau astoņos.',
        'Tavs īstais vīrietis ir tur ārā, un ja tu viņu nenogrābsi, to izdarīs cita.',
        'Teicu zāles čalim, lai uzlabo mantu.',
        'Tev ir skaista pakaļa.',
        'Tev pienācis gals, mans skolotāj.',
        'Tie ir sūdīgi.',
        'Tik daudz šņabja, cik vēlies, un vēl tūkstotis rubļu.',
        'Trijos naktī kādam sūtīju ziņu, lai mani piekauj.',
        'Tu domā, ka es tevi gribu!',
        'Tu gribi lai es iedzeru vīna glāzi - uz tavas terases?',
        'Tu izskaties seksīgi.',
        'Tu izturies kā mērglis.',
        'Tu nepīpē veipu?',
        'Tu od pēc zāles.',
        'Tu sadzēries ļoti ātri.',
        'Tu sarīkoji avāriju, nonāvēji dzīvnieku. To rāda visās ziņās.',
        'Tu varēji mani nošaut!',
        'Tu varētu būt pirmā pievilcīgā sieviete manā dzīvē, ar ko es neesmu gribējis pārgulēt.',
        'Tu, es un tas neglītais armēnis teltī.',
        'Tur ir tik daudz sūdainu grāmatu.',
        'Tur skaļruņus, paklājus, galdu glāžu spēlei un alus pongam.',
        'Tāpat kā es vienmēr izdzīvoju, tu vienmēr mirsti.',
        'Tātad tu saki, ka vīrietis var būt draugs sievietei, kura viņam nav pievilcīga?',
        'Tēvs mācītājs, viņa staigā pa ballītēm, izliekas atslēgusies.',
        'Tēvs žūpa, dēls nabags.',
        'Tūlīt atlidos mani pajoliņi un par trim rubļiem visu saķimerēs.',
        'Un atstāji viņam stroķi?',
        'Un tu sapīpējies.',
        'Uz Maskavu brauc zaudēt nevainību, taču zaudē naudu, dokumentus un mobilo telefonu.',
        'Uzņēmuši sūdu, bet čunguru grābj liekšķerēm.',
        'Vai ar šitā producenta laipnību visas skuķenes tiek kinītī?',
        'Vai daudz cilvēku mēdz ierasties bez drēbēm?',
        'Vai jums ir Asiņainā Mērija?',
        'Vai tas ir kanibālisms?',
        'Vai tu kādreiz domā par nāvi?',
        'Vai vīrietis nevar pateikt sievietei, ka viņa ir pievilcīga bez tālāka nolūka?',
        'Vai, atrodot savu dzīves vīrieti, tu pazaudēji spēju strādāt?',
        'Vairs ne, mērgli.',
        'Vecā labprāt uzsēstos tev uz ģīmja.',
        'Velc savu pakaļu sūda treilerā.',
        'Velc šurp viņu un atstutē pret dīvānu.',
        'Vienkārši sievietes un vīrieši nevar būt draugi, jo vienmēr pa vidu ir seksuālā puse.',
        'Viņam vajag sievieti. Viņš ir vientuļš.',
        'Viņš ir kretīns.',
        'Vīrieši un sievietes nevar būt draugi, jo vienmēr pa vidu ir seksuālā puse.',
        'Šķiet, viņa bija iemīlējusies tavā tētī un tagad ir iemīlējusies tevī.'
      )
  `);
};

export const down = async function (): Promise<any> {
  return null;
};
