export const up = async function (db: any): Promise<any> {
  await db.runSql(
    `
      ALTER TABLE accents ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE achievements ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE ages ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE awards ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE challenges ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE clip_demographics ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE clips ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE custom_goals ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE datasets ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE demographics ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE deprecated_users ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE downloaders ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE earn ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE enroll ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE genders ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE language_requests ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE locale_datasets ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE locales ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE migrations ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE reached_goals ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE reported_clips ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE reported_sentences ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE requested_languages ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE sentences ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE sessions ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE skipped_clips ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE skipped_sentences ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE streaks ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE taxonomies ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE taxonomy_entries ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE taxonomy_terms ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE teams ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_accents ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_activities ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_locale_buckets ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_newsletter_prefs ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_takeouts ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_client_variants ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE user_clients ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE variants ADD COLUMN corpus_id VARCHAR(255);
      ALTER TABLE votes ADD COLUMN corpus_id VARCHAR(255);
    `
  );

  await db.runSql(`
      UPDATE accents SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE achievements SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE ages SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE awards SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE challenges SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE clip_demographics SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE clips SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE custom_goals SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE datasets SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE demographics SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE deprecated_users SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE downloaders SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE earn SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE enroll SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE genders SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE language_requests SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE locale_datasets SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE locales SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE migrations SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE reached_goals SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE reported_clips SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE reported_sentences SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE requested_languages SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE sentences SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE sessions SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE skipped_clips SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE skipped_sentences SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE streaks SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE taxonomies SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE taxonomy_entries SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE taxonomy_terms SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE teams SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_accents SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_activities SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_locale_buckets SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_newsletter_prefs SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_takeouts SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_client_variants SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE user_clients SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE variants SET corpus_id = 'falak' WHERE corpus_id IS NULL;
      UPDATE votes SET corpus_id = 'falak' WHERE corpus_id IS NULL;
    `);

  return null;
};

export const down = async function (db: any): Promise<any> {
  return db.runSql(
    `
      ALTER TABLE accents DROP COLUMN corpus_id;
      ALTER TABLE achievements DROP COLUMN corpus_id;
      ALTER TABLE ages DROP COLUMN corpus_id;
      ALTER TABLE awards DROP COLUMN corpus_id;
      ALTER TABLE challenges DROP COLUMN corpus_id;
      ALTER TABLE clip_demographics DROP COLUMN corpus_id;
      ALTER TABLE clips DROP COLUMN corpus_id;
      ALTER TABLE custom_goals DROP COLUMN corpus_id;
      ALTER TABLE datasets DROP COLUMN corpus_id;
      ALTER TABLE demographics DROP COLUMN corpus_id;
      ALTER TABLE deprecated_users DROP COLUMN corpus_id;
      ALTER TABLE downloaders DROP COLUMN corpus_id;
      ALTER TABLE earn DROP COLUMN corpus_id;
      ALTER TABLE enroll DROP COLUMN corpus_id;
      ALTER TABLE genders DROP COLUMN corpus_id;
      ALTER TABLE language_requests DROP COLUMN corpus_id;
      ALTER TABLE locale_datasets DROP COLUMN corpus_id;
      ALTER TABLE locales DROP COLUMN corpus_id;
      ALTER TABLE migrations DROP COLUMN corpus_id;
      ALTER TABLE reached_goals DROP COLUMN corpus_id;
      ALTER TABLE reported_clips DROP COLUMN corpus_id;
      ALTER TABLE reported_sentences DROP COLUMN corpus_id;
      ALTER TABLE requested_languages DROP COLUMN corpus_id;
      ALTER TABLE sentences DROP COLUMN corpus_id;
      ALTER TABLE sessions DROP COLUMN corpus_id;
      ALTER TABLE skipped_clips DROP COLUMN corpus_id;
      ALTER TABLE skipped_sentences DROP COLUMN corpus_id;
      ALTER TABLE streaks DROP COLUMN corpus_id;
      ALTER TABLE taxonomies DROP COLUMN corpus_id;
      ALTER TABLE taxonomy_entries DROP COLUMN corpus_id;
      ALTER TABLE taxonomy_terms DROP COLUMN corpus_id;
      ALTER TABLE teams DROP COLUMN corpus_id;
      ALTER TABLE user_client_accents DROP COLUMN corpus_id;
      ALTER TABLE user_client_activities DROP COLUMN corpus_id;
      ALTER TABLE user_client_locale_buckets DROP COLUMN corpus_id;
      ALTER TABLE user_client_newsletter_prefs DROP COLUMN corpus_id;
      ALTER TABLE user_client_takeouts DROP COLUMN corpus_id;
      ALTER TABLE user_client_variants DROP COLUMN corpus_id;
      ALTER TABLE user_clients DROP COLUMN corpus_id;
      ALTER TABLE variants DROP COLUMN corpus_id;
      ALTER TABLE votes DROP COLUMN corpus_id;
    `
  );
};
