contact_links:
- name: "\U0001F5E3 Join the Community Chat"
  url: https://matrix.to/#/#common-voice:mozilla.org
  about: "If you have quick question or would like to connect with contributors, join our element chat"
