FROM node:18-bookworm

# Allow exposing HTTP endpoint
EXPOSE 9090

# Install dependencies
RUN apt-get update && \
    apt-get install -y apt-transport-https build-essential cmake && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y yarn ffmpeg vim

# Setup work directory
WORKDIR /app

COPY package.json yarn.lock ./

# Install yarn dependencies
RUN yarn

COPY . .

# Run build
RUN yarn build

RUN cp -r /app/web/img /app/web/dist/

# Create directory for storing logs
RUN mkdir /app/logs

# Default command to start the server
CMD yarn start 2>&1 | tee /app/logs/voice-server.log