FROM node:18-bookworm

# Allow exposing HTTP endpoint
EXPOSE 9090

# Install dependencies
RUN apt-get update && \
    apt-get install -y apt-transport-https build-essential cmake && \
    apt-get install --no-install-recommends -y ffmpeg vim

# Setup work directory
WORKDIR /app

# Copy root package.json and lock
COPY package.json package-lock.json ./

# Install root dependencies
RUN npm install

# Copy the rest of the application
COPY . .
# Copy .env-local-docker
COPY .env-local-docker ./
# Install dependencies for each subproject
RUN cd common && npm install && cd .. && \
    cd server && npm install && cd .. && \
    cd web && npm install && cd .. && \
    cd maintenance && npm install && cd ..

# Run build
RUN npm run build

# Copy web images to the dist folder
RUN cp -r /app/web/img /app/web/dist/

# Create directory for storing logs
RUN mkdir /app/logs

# Default command to start the server
CMD npm run start 2>&1 | tee /app/logs/voice-server.log