#!/bin/bash -l

WORKDIR=/opt/common-voice-bundler
EXPECTED_USER="voice-data"

if [ "$USER" != "$EXPECTED_USER" ]; then
  echo "Please run this script as $EXPECTED_USER"
  exit 2
fi

# Protect ourselves against concurrent execution, wait for exclusive lock before proceeding
[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -e "$0" "$0" "$@"

# Taking ourselves out of the rotation for the duration
INSTANCE_ID=$(ec2metadata --instance-id)
REGION=$(nubis-region)
ASG=$(aws --region "$REGION" autoscaling describe-auto-scaling-instances --instance-ids="$INSTANCE_ID" | jq .AutoScalingInstances[0].AutoScalingGroupName -r)

cleanup () {
  echo "Going back in service in the rotation"
  aws --region "$REGION" autoscaling exit-standby --auto-scaling-group-name "$ASG" --instance-ids="$INSTANCE_ID"
}

trap cleanup EXIT

echo "Taking ourselves out of rotation"
aws --region "$REGION" autoscaling enter-standby --auto-scaling-group-name "$ASG" --should-decrement-desired-capacity --instance-ids "$INSTANCE_ID"

echo "Running bundling in $WORKDIR"

pushd $WORKDIR 2>/dev/null || exit 1

yarn start

RV=$?

popd 2>/dev/null || exit 1

exit $RV
