#!/bin/bash -l

export PATH=/usr/local/bin:$PATH

NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)

PROJECT_VERSION=$(awk '{print $2}' < "/etc/$NUBIS_PROJECT-release")

KV_PREFIX="$NUBIS_PROJECT-$NUBIS_ENVIRONMENT/$NUBIS_ENVIRONMENT/config"

if [ "$PROJECT_VERSION" != "" ]; then
  consulate kv set "$KV_PREFIX/Version" "$PROJECT_VERSION"
fi
