export const DAILY_GOALS = Object.freeze({
  speak: [1200, 2500],
  listen: [2400],
});

export const BENEFITS = [
  'rich-data',
  'improve-audio',
  'keep-track',
  'compare-progress',
  'view-goals',
  'join-newsletter',
];

export const WHATS_PUBLIC = [
  'email-not-public',
  'recordings-and-locale-public',
  'username-optin-public',
  'demographic-deidentified-clarity-2',
  'username-email-not-demographic',
];

// @TODO: use this constant in other files where we use this email
export const COMMON_VOICE_EMAIL = 'info@ksaa.gov.sa';

export const COUNTRIES = [
  { name: 'المملكة العربية السعودية', value: 'Saudi Arabia' },
  { name: 'الإمارات العربية المتحدة', value: 'United Arab Emirates' },
  { name: 'مصر', value: 'Egypt' },
  { name: 'الأردن', value: 'Jordan' },
  { name: 'الكويت', value: 'Kuwait' },
  { name: 'لبنان', value: 'Lebanon' },
  { name: 'قطر', value: 'Qatar' },
  { name: 'البحرين', value: 'Bahrain' },
  { name: 'عمان', value: 'Oman' },
  { name: 'المغرب', value: 'Morocco' },
  { name: 'الولايات المتحدة', value: 'United States' },
  { name: 'كندا', value: 'Canada' },
  { name: 'المملكة المتحدة', value: 'United Kingdom' },
  { name: 'فرنسا', value: 'France' },
  { name: 'ألمانيا', value: 'Germany' },
  { name: 'إيطاليا', value: 'Italy' },
  { name: 'إسبانيا', value: 'Spain' },
  { name: 'أستراليا', value: 'Australia' },
  { name: 'نيوزيلندا', value: 'New Zealand' },
  { name: 'البرازيل', value: 'Brazil' },
  { name: 'الأرجنتين', value: 'Argentina' },
  { name: 'جنوب أفريقيا', value: 'South Africa' },
  { name: 'الصين', value: 'China' },
  { name: 'اليابان', value: 'Japan' },
  { name: 'كوريا الجنوبية', value: 'South Korea' },
  { name: 'الهند', value: 'India' },
  { name: 'باكستان', value: 'Pakistan' },
  { name: 'إندونيسيا', value: 'Indonesia' },
  { name: 'تركيا', value: 'Turkey' },
  { name: 'إيران', value: 'Iran' },
  { name: 'روسيا', value: 'Russia' },
  { name: 'المكسيك', value: 'Mexico' },
  { name: 'الفلبين', value: 'Philippines' },
  { name: 'تايلاند', value: 'Thailand' },
  { name: 'فيتنام', value: 'Vietnam' },
  { name: 'سنغافورة', value: 'Singapore' },
  { name: 'ماليزيا', value: 'Malaysia' },
  { name: 'نيجيريا', value: 'Nigeria' },
  { name: 'كينيا', value: 'Kenya' },
  { name: 'غانا', value: 'Ghana' },
  { name: 'تنزانيا', value: 'Tanzania' },
  { name: 'الجزائر', value: 'Algeria' },
  { name: 'تونس', value: 'Tunisia' },
  { name: 'ليبيا', value: 'Libya' },
  { name: 'العراق', value: 'Iraq' },
  { name: 'سوريا', value: 'Syria' },
  { name: 'السودان', value: 'Sudan' },
  { name: 'الصومال', value: 'Somalia' },
  { name: 'اليمن', value: 'Yemen' },
  { name: 'أفغانستان', value: 'Afghanistan' },
  { name: 'السويد', value: 'Sweden' },
  { name: 'النرويج', value: 'Norway' },
  { name: 'الدنمارك', value: 'Denmark' },
  { name: 'فنلندا', value: 'Finland' },
  { name: 'سويسرا', value: 'Switzerland' },
  { name: 'بلجيكا', value: 'Belgium' },
  { name: 'هولندا', value: 'Netherlands' },
  { name: 'النمسا', value: 'Austria' },
  { name: 'اليونان', value: 'Greece' },
  { name: 'البرتغال', value: 'Portugal' },
  { name: 'بولندا', value: 'Poland' },
  { name: 'التشيك', value: 'Czech Republic' },
  { name: 'المجر', value: 'Hungary' },
  { name: 'رومانيا', value: 'Romania' },
  { name: 'بلغاريا', value: 'Bulgaria' },
  { name: 'أوكرانيا', value: 'Ukraine' },
  { name: 'مالطا', value: 'Malta' },
  { name: 'آيسلندا', value: 'Iceland' },
  { name: 'فنزيولا', value: 'Venezuela' },
  { name: 'تشيلي', value: 'Chile' },
  { name: 'بيرو', value: 'Peru' },
  { name: 'كولومبيا', value: 'Colombia' },
  { name: 'أوروجواي', value: 'Uruguay' },
  { name: 'بوليفيا', value: 'Bolivia' },
  { name: 'الإكوادور', value: 'Ecuador' },
  { name: 'باراغواي', value: 'Paraguay' },
  { name: 'كوستاريكا', value: 'Costa Rica' },
  { name: 'بنما', value: 'Panama' },
  { name: 'السلفادور', value: 'El Salvador' },
  { name: 'هندوراس', value: 'Honduras' },
  { name: 'غواتيمالا', value: 'Guatemala' },
  { name: 'نيكاراغوا', value: 'Nicaragua' },
  { name: 'هايتي', value: 'Haiti' },
  { name: 'جامايكا', value: 'Jamaica' },
  { name: 'الباهاما', value: 'Bahamas' },
  { name: 'كوبا', value: 'Cuba' },
  { name: 'باربادوس', value: 'Barbados' },
  { name: 'ترينيداد وتوباغو', value: 'Trinidad and Tobago' },
  { name: 'بورتوريكو', value: 'Puerto Rico' },
];