---
name: Build and Push to GAR

on:
  push:
    tags:
      - 'sandbox-v*.*.*'
      - 'stage-v*.*.*'
      - 'release-v*.*.*'

jobs:
  build_and_push:
    name: Build and Push Image to GAR
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4

      - name: Retrieve Git Commit SHA
        id: vars
        run: |
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "git_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Deployment Environment from Tag
        id: deploy_env
        run: |
          TAG="${{ steps.vars.outputs.git_tag }}"
          DEPLOY_ENV=""
          if [[ "$TAG" == release-v* ]]; then
            DEPLOY_ENV="production"
          elif [[ "$TAG" == stage-v* ]]; then
            DEPLOY_ENV="staging"
          elif [[ "$TAG" == sandbox-v* ]]; then
            DEPLOY_ENV="sandbox"
          fi
          echo "environment=${DEPLOY_ENV}" >> $GITHUB_OUTPUT

      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          service_account: artifact-writer@${{ secrets.GAR_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ secrets.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Authenticate with Docker Registry
        id: docker-login
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          tags: |
            us-docker.pkg.dev/${{secrets.GAR_DOCKER_IMAGE_PATH}}:${{steps.vars.outputs.git_tag}}
          push: true
          build-args: |
            COMMIT=${{ steps.vars.outputs.commit_sha }}
            TAG=${{ steps.vars.outputs.git_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
